export const MAIN = '#ffeef2'
export const NAVY = '#173753'
export const RED = '#F25F5C'
export const GREEN = '#A5FFD6'
export const BLUE = '#7D8CC4'
export const BLUE_ACTIVE = '#7b74b8'
export const RED_ACTIVE = '#e05252'
export const MAIN_ACTIVE = '#f0dde2'
